#!python

import os
import sys

if (len(sys.argv)!=2):
   print "illegal number of arguments"
   exit(1)

os.system("./vs-asm test_progs/"+sys.argv[1]+" > program.mem")
os.system("make > /dev/null")
os.system("./simv > test_out")
os.system("./simv_gold > gold_out")
print "diff: "
os.system("diff test_out gold_out")

